Document: amqpcpp
Title: Debian amqpcpp Manual
Author: <insert document author here>
Abstract: This manual describes what amqpcpp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amqpcpp/amqpcpp.sgml.gz

Format: postscript
Files: /usr/share/doc/amqpcpp/amqpcpp.ps.gz

Format: text
Files: /usr/share/doc/amqpcpp/amqpcpp.text.gz

Format: HTML
Index: /usr/share/doc/amqpcpp/html/index.html
Files: /usr/share/doc/amqpcpp/html/*.html
